services:
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    depends_on:
#      - shareddb
#    restart: unless-stopped
  web:
    image: nginx
    container_name:
      web
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: always
  shareddb:
    container_name: shareddb
    image: postgres
    environment:
      POSTGRES_USER: shared
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shared
      PGDATA: /data/postgres
    volumes:
      - shareddb:/data/postgres
      - ./shared-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  files-manager:
    build: ./files-manager
    container_name: files-manager
    ports:
      - "10500:10500"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - shareddb
  white-rabbit:
    build: ../WhiteRabbit
    container_name:
      white-rabbit
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - shareddb
      - files-manager
  cdm-builder:
    build: 
       context: ../ETL-CDMBuilder
       dockerfile: ../ETL-CDMBuilder/source/org.ohdsi.cdm.presentation.builderwebapi/Dockerfile
    container_name:
      cdm-builder
    ports:
      - "9000:9000"
    depends_on:
      - shareddb
      - files-manager
      - vocabularydb
  r-serve:
    build:
      context: ../DataQualityDashboard/R
      args:
        prop: docker
    container_name:
      r-serve
    ports:
      - "6311:6311"
    depends_on:
      - shareddb
  data-quality-dashboard:
    build:
      context: ../DataQualityDashboard
    container_name:
      data-quality-dashboard
    ports:
      - "8001:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - shareddb
      - files-manager
  user:
    build: ./user
    command: python /app/main.py
    container_name: user
    environment:
      USER_ENV: Docker
      TOKEN_SECRET_KEY: Perseus-Arcadia
    env_file:
      - user/user-envs.txt
    ports:
      - "5001:5001"
    depends_on:
      - shareddb
  sourcedb:
    container_name: sourcedb
    image: postgres
    environment:
      POSTGRES_USER: perseus
      POSTGRES_PASSWORD: password
      POSTGRES_DB: source
      PGDATA: /data/postgres
    volumes:
      - sourcedb:/data/postgres
    ports:
      - "5433:5432"
  perseus:
    build: ./perseus-api
    command: python /app/main.py
    container_name: perseus
    environment:
      PERSEUS_ENV: Docker
    ports:
      - "5000:5000"
    depends_on:
      - sourcedb
      - shareddb
      - files-manager
  vocabularydb:
    build: ./vocabulary-db
    container_name: vocabularydb
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "vocabulary", "-U", "perseus" ]
      timeout: 60s
      interval: 30s
      retries: 10
    volumes:
      - vocabularydb:/data/postgres
    ports:
      - "5431:5432"
  frontend:
    build:
      context: ./UI
      args:
        env: dev
    container_name:
      frontend
    ports:
      - "4200:4200"
  solr:
    image: solr
    container_name: solr
    command:
      - solr-precreate
      - athena
      - /opt/solr/server/solr/configsets/athena/conf
    ports:
      - "8983:8983"
    volumes:
      - solr:/var/solr
      - ./solr/athena:/opt/solr/server/solr/configsets/athena
      - ./solr/postgresql-42.2.19.jar:/opt/solr/dist/postgresql-42.2.19.jar
  athena:
    build: ./athena-api
    command: python /app/main.py
    container_name: athena
    environment:
      ATHENA_ENV: Docker
    ports:
      - "5002:5002"
    depends_on:
      - solr
#  usagi-api:
#    build: ./usagi-api
#    command: python /app/main.py
#    container_name: usagi-api
#    environment:
#      USAGI_ENV: Local
#    ports:
#      - "5150:5150"
#    depends_on:
#      - shareddb
#    networks:
#      - usagi
#      - shareddb
#      - vocabularydb

volumes:
  shareddb:
  sourcedb:
  vocabularydb:
  solr:
#  pgadmin:
