services:
  web:
    build: ./nginx
    image:
      perseushub.arcadialab.ru/web:latest
    container_name:
      web
    ports:
      - "80:80"
    restart: always
  shareddb:
    build: ./shared-db
    image:
      perseushub.arcadialab.ru/shareddb:latest
    container_name: shareddb
    volumes:
      - shareddb:/data/postgres
    ports:
      - "5432:5432"
  files-manager:
    build: ./files-manager
    image:
      perseushub.arcadialab.ru/files-manager:latest
    container_name: files-manager
    ports:
      - "10500:10500"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - shareddb
  user:
    build: ./user
    image:
      perseushub.arcadialab.ru/user:latest
    container_name: user
    environment:
      USER_ENV: Docker
    env_file:
      - user/user-envs.txt
    ports:
      - "5001:5001"
    depends_on:
      - shareddb
  backend:
    build: ./perseus-api
    image:
      perseushub.arcadialab.ru/backend:latest
    container_name: backend
    environment:
      PERSEUS_ENV: Docker
    ports:
      - "5000:5000"
    depends_on:
      - shareddb
      - files-manager
  frontend:
    build:
      context: ./UI
      args:
        env: prod
    image:
      perseushub.arcadialab.ru/frontend:latest
    container_name:
      frontend
    ports:
      - "4200:4200"
  white-rabbit:
    build: ../WhiteRabbit
    image:
      perseushub.arcadialab.ru/white-rabbit:latest
    container_name:
      white-rabbit
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - shareddb
      - files-manager
  vocabularydb:
    build: ./vocabulary-db
    image:
      perseushub.arcadialab.ru/vocabularydb:latest
    container_name: vocabularydb
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "vocabulary", "-U", "perseus" ]
      timeout: 60s
      interval: 30s
      retries: 10
    volumes:
      - vocabularydb:/data/postgres
    ports:
      - "5431:5432"
  cdm-builder:
    build: ../ETL-CDMBuilder
    image:
      perseushub.arcadialab.ru/cdm-builder:latest
    container_name:
      cdm-builder
    ports:
      - "9000:9000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - shareddb
      - files-manager
      - vocabularydb
  solr:
    build: ./solr
    image:
      perseushub.arcadialab.ru/solr:latest
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - solr:/var/solr
    depends_on:
      - vocabularydb
  athena:
    build: ./athena-api
    image:
      perseushub.arcadialab.ru/athena:latest
    container_name: athena
    environment:
      ATHENA_ENV: Docker
    ports:
      - "5002:5002"
    depends_on:
      - solr
  usagi:
    build: ./usagi-api
    image:
      perseushub.arcadialab.ru/usagi:latest
    command: python /app/main.py
    container_name: usagi
    environment:
      USAGI_ENV: Docker
    ports:
      - "5003:5003"
    depends_on:
      - shareddb
      - solr
  r-serve:
    build:
      context: ../DataQualityDashboard/R
      args:
        prop: docker
    image:
      perseushub.arcadialab.ru/r-serve:latest
    container_name:
      r-serve
    ports:
      - "6311:6311"
    depends_on:
      - shareddb
  data-quality-dashboard:
    build:
      context: ../DataQualityDashboard
    image:
      perseushub.arcadialab.ru/data-quality-dashboard:latest
    container_name:
      data-quality-dashboard
    ports:
      - "8001:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - shareddb
      - files-manager
      - r-serve

volumes:
  shareddb:
  vocabularydb:
  solr:
