server:
  port: 8002
  error:
    include-message: always
  servlet:
    context-path: /auth

spring:
  application:
    name: Auth
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${AdClientId}
        app-id-uri: api://${AdClientId}
      keyvault:
        secret:
          property-source-enabled: true
          property-sources:
            -
              credential:
                client-id: ${AZURE_CLIENT_ID}
              endpoint: https://kv-perseus.vault.azure.net/
              profile:
                tenant-id: ${AZURE_TENANT_ID}
