FROM nginx

RUN apt-get update \
    && apt-get install -y --no-install-recommends openssh-server \
    && export ROOTPASS=$(head -c 12 /dev/urandom |base64 -) && echo "root:$ROOTPASS" | chpasswd

COPY nginx.conf /etc/nginx/nginx.conf
COPY dist /usr/share/nginx/html
COPY sshd_config /etc/ssh/
COPY entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

EXPOSE 4200
EXPOSE 2222

CMD ["./entrypoint.sh"]
